### ISSUE TITLE
Transcript ep 42 "Ron Evans" showing up as "Paul Orlando"

### ISSUE THREAD

**Issue by harveysanders** [thechangelog/transcripts#1174]
For some reason, the [transcript for ep 42](https://changelog.com/friends/42#transcript-18) has Ron Evans' lines labeled with "Paul Orlando". 
![image](https://github.com/thechangelog/transcripts/assets/9354822/ef66ca8f-844c-4e90-92fd-940aeaa2c5e6)

It's correct in the transcript file though:
https://github.com/thechangelog/transcripts/blob/master/friends/changelog--friends-42.md

Great show, as always!

**Comment by jerodsanto** [comment]
Thanks for letting us know! It must've been fixed on GitHub after the fact and had the webhook fail for whatever reason. I just pulled a refresh on the site and now all is well once again ✌️
