### ISSUE TITLE
[unintelligible] fixes for 532

### ISSUE THREAD

**Issue by kcoul** [thechangelog/transcripts#1175]
Not 100% confident in all of them, but here you go:

https://github.com/thechangelog/transcripts/blob/master/podcast/the-changelog-532.md
https://changelog.com/podcast/532#transcript

00:09:31:10 multithreading support
00:10:22.00 the tools, had the
00:10:44.29 Jun-shu [rich sake] ???
00:11:11.29 , back at the repo
00:36:55.16 await the
00:45:37.09 NVBLAS
00:51:26.13 the worst day... ???
00:54:55.13 text (later it should also read "I personally haven't seen... anyway, let's not go in this direction")

**Comment by jerodsanto** [comment]
Awesome! Are you up for opening up a PR with the fixes you are confident in replacing the [unintelligible] portions? That'd be great!

**Comment by kcoul** [comment]
Here you go! https://github.com/thechangelog/transcripts/pull/1176

**Comment by jerodsanto** [comment]
Whoops forgot to close this!
