### ISSUE TITLE
Improve a transcript

### ISSUE THREAD

**Issue by chris48s** [thechangelog/transcripts#23]
* Pick an episode of a changelog podcast from https://changelog.com/ and find the corresponding transcript in this repository: https://github.com/thechangelog/transcripts

* Listen to the podcast and improve the transcript by:

  * Replacing the keyword 'unintelligible' with the correct word/phrase
  * Adding links to referenced URLs, projects, etc.
  * Adding timestamps to key/beloved statements and sections
  * Fixing typos

* Submit a PR with your changes

**Comment by jerodsanto** [comment]
What do you mean by 'claim episodes', @brucellino?

**Comment by brucellino** [comment]
Sorry, should have been a bit more explicit. I mean somehow announce  'yo everyone, I got this episode, so hold off your contribs at least until I send my PR, ok ?' 
Feels like otherwise it might be a bit of a conflictfest.

**Comment by jerodsanto** [comment]
Good thinking, but that isn't a problem we've had just yet. 😄

I could see an issue down the road, especially with the most recent episodes being more popular to work on than the older ones, but for now just go ahead and dive in. If there are conflicts we'll merge 'em and figure out a way to avoid in the future.

**Comment by jdillard** [comment]
If someone wants an low barrier way to contribute, here is a list of unintelligibles to fix: https://github.com/thechangelog/transcripts/search?utf8=%E2%9C%93&q=unintelligible

**Comment by jerodsanto** [comment]
@jdillard good thinking! I added that to the README for easy access. ✊

**Comment by MissMeg** [comment]
Hi! 

I had a quick question on repeated phrases when updating a transcript. For instance, if the interviewee kind of stumbles and says "Yeah, I have some... some thoughts on that." Do you want that noted or just leave it as "Yeah, I have some thoughts on that."? 

Essentially, I am trying to gauge how exact you want the transcript to be with repeated phrases, "uh"s, "um"s, etc.

Currently, it is "Yeah, I have some thoughts on that." in the transcript. (Changelog-350 when Yaw Anokwa starts talking)

Thank you!

**Comment by jerodsanto** [comment]
Great question! We aim for **readability** over accuracy in those circumstances. It does **not** have to be verbatim, especially with "uhms", "ahhs", and other pause words/sounds.
