### ISSUE TITLE
Making a PR early to get a rough cut of the transcript up

### ISSUE THREAD

**Issue by jacebenson** [thechangelog/transcripts#390]
I started to take a stab at the 327 transciption and ran the audio through a private youtube video to get it.  The transcription is actually not that bad, just need to make the line breaks and add who said what with some minor typos.

Would this be alright for an initial go at the transcription.  I mean could I make a PR and others could contribute then  at that time to the rough cut.

https://github.com/jacebenson/transcripts/blob/transcript-327/podcast/the-changelog-327.md

**Comment by jerodsanto** [comment]
It's definitely not terrible, but it'll take a lot of massaging before it's mergeable/usable. Are you up for that?
